version: '3'

services:
  supertokens:
    image: supertokens/supertokens-postgresql:3.6
    environment:
      POSTGRESQL_CONNECTION_URI: 'postgresql://postgres:postgres@db:5432/nboxauth'
      POSTGRESQL_TABLE_SCHEMA: 'supertokens'
      DISABLE_TELEMETRY: 'true'
    depends_on:
      - db

  db:
    image: postgres:13.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nboxauth

  test:
    image: node:16
    command: bash -c "npm run test && npm run test:e2e"
    volumes:
      - ./:/app:ro
    working_dir: /app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/nboxauth
      SUPERTOKENS_CORE: http://supertokens:3567
    depends_on:
      - db
      - supertokens
