name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  extractversion:
    name: Extract version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extractversion.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Extract version from Git
        id: extractversion
        run: echo "::set-output name=version::$(git describe)"

  build-publish-release:
    name: Build & publish container
    needs: extractversion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract branch/tag name
        run: |
          echo "branch_tag_name=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Build and push container
        uses: docker/build-push-action@v2
        env:
          VERSION: ${{ needs.extractversion.outputs.version }}
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/nbox-auth:${{ needs.extractversion.outputs.version }}

  publish:
    name: Publish release
    needs: build-publish-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create .artifacts dir
        run: mkdir .artifacts
      - name: Generate Changelog
        run: git log --pretty="format:[%h] %s" $(git describe --tags --abbrev=0 @^)..@ > .artifacts/CHANGELOG.txt
      - name: Publish Changelog
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: .artifacts/**
          body_path: .artifacts/CHANGELOG.txt
